#!/bin/bash

set -x

export PATH=".:$PATH"

if [[ ! -d build ]] ; then
  echo "Already cleaned, do Nothing"
  exit
fi

if [[ "$1" == '-a' ]] ; then
  rm -r build
else
  cd build/bin
  #./w3_clean
  ./w3_new all
fi
