#!/bin/csh -f

set PATH=".:$PATH"

if ( ! -d build ) then
  echo "Already cleaned, do Nothing"
  exit
endif

if ( "$1" == '-a' ) then
  rm -r build
else
  cd build/bin
  #./w3_clean
  ./w3_new all
endif
