#!/bin/csh -f

set PATH=".:$PATH"

if ($#argv == 1) then
  set MACHINE=$1
else if ($#argv == 0) then
  echo "Warning: assuming on jet machine"
  set MACHINE=jet
else
  echo "Usage: $0 machine"
  echo "Install compile WW3 on this machine"
  echo "Example: $0 jet"
  exit 1
endif

if ( ! -d build ) then
  echo "Warning: Need to run ./configure first"
  echo "Exiting: do nothing"
  exit 1
endif

cd build/

if ( ! -d bin ) then

# Link install script and run install 
ln -sf svn/model/bin/install_ww3_svn .

# Install WW3 into the build directory
./install_ww3_svn << EOF
y
L
y
n
y
n
EOF

endif

cd bin

# choose correct comp and link files
# can be done in the configure step
cp comp.Intel_$MACHINE comp
cp link.Intel_$MACHINE link

# use proper switch file
cp switch_NCEP_st4 switch
#cp switch_NCEP_st2 switch

# compile WW3 
./make_MPI

